### PR TITLE
This commit changes/modifies:

### PR DESCRIPTION
**Pull request by gbowne1**
- ACKNOWLEDGEMENTS.md
- AUTHORS.md
- CODEOWNERS (Adds Owners)
- CODESTYLE.md
- CONTENT_CREATION.md
- DEVSETUP.md
- DISCORD_RULES.md
- FAQ.md
- [ ] GROUP_POLICY_DRAFT.md
- ISSUE_TEMPLATE.md
- MEE6_ENTRANCE_DESC.md
- PULL_REQUEST_TEMPLATE. (fixes Link)
- TODO.md

The main change adds draft text to GROUP_POLICY_DRAFT.md for review.

Issue Number: N/A

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

This PR adds draft text to GROUP_POLICY_DRAFT.md for review, discussion and final implementation and pushed to the /docs project in our Organization repository.

- [ ] Fixes Issue #?

### Contributor Checklist

- [ ] [Review Contribution Guidelines](https://github.com/taotnpwaft/metadata/blob/main/CONTRIBUTING.md)
- [ ] Make sure your code has been tested.
- [ ] Make sure any workflows and/or GitHub Actions and any configured task runners have been run and have passed.
- [x] Make sure your code follows the code style guides for the languages you have used
- [x] Proofread your code for spelling / typographical errors.  {Perhaps install a spelling/typo extension}
- [ ] Include links to any documentation, especially on 2nd, 3rd party sites.
- [ ] If your code runs in the browser, check the browser console.  Also make sure it renders correctly.
- [ ] Make sure libraries are up to date.

### CODE REVIEW

**Review by gbowne1 — COMMENTED** [review]
This PR adds more draft text to:
GROUP_POLICY_DRAFT.md

All other changes to markdown documentation are minor and include fixing and adding links.

**Comment by gbowne1** [comment]
Please see: https://github.com/taotnpwaft/metadata/discussions/13 for more information.

**Review by hitblast — APPROVED** [review]
LGTM!

**Comment by gbowne1** [comment]
Thanks for the review @hitblast. :-)

Merged.

**Pull request merged**
